-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-01-31 20:24:41 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE aeroport (
    id_aeroport  INTEGER NOT NULL,
    nume         VARCHAR2(30),
    adresa       VARCHAR2(30),
    oras_id_oras INTEGER NOT NULL
);

ALTER TABLE aeroport ADD CONSTRAINT aeroport_pk PRIMARY KEY ( id_aeroport );

CREATE TABLE bilet (
    id_bilet          INTEGER NOT NULL,
    denumire          VARCHAR2(30),
    zbor_id_zbor      INTEGER NOT NULL,
    clienti_id_client INTEGER NOT NULL
);

ALTER TABLE bilet ADD CONSTRAINT bilet_pk PRIMARY KEY ( id_bilet );

CREATE TABLE clienti (
    id_client    INTEGER NOT NULL,
    nume         VARCHAR2(30) NOT NULL,
    prenume      VARCHAR2(30) NOT NULL,
    adresa       VARCHAR2(30),
    "Nr telefon" NUMBER(10) NOT NULL,
    email        VARCHAR2(30)
);

ALTER TABLE clienti ADD CONSTRAINT clienti_pk PRIMARY KEY ( id_client );

CREATE TABLE companie (
    id_companie INTEGER NOT NULL,
    nume        VARCHAR2(30),
    descriere   VARCHAR2(30)
);

ALTER TABLE companie ADD CONSTRAINT companie_pk PRIMARY KEY ( id_companie );

CREATE TABLE oras (
    id_oras INTEGER NOT NULL,
    nume    VARCHAR2(30),
    tara    VARCHAR2(30)
);

ALTER TABLE oras ADD CONSTRAINT oras_pk PRIMARY KEY ( id_oras );

CREATE TABLE zbor (
    id_zbor               INTEGER NOT NULL,
    "Data plecare"        DATE,
    "Data sosire"         DATE,
    aeroport_id_aeroport  INTEGER NOT NULL,
    companie_id_companie  INTEGER NOT NULL,
    pret_zbor             FLOAT,
    aeroport_id_aeroport2 INTEGER NOT NULL
);

ALTER TABLE zbor ADD CONSTRAINT zbor_pk PRIMARY KEY ( id_zbor );

ALTER TABLE aeroport
    ADD CONSTRAINT aeroport_oras_fk FOREIGN KEY ( oras_id_oras )
        REFERENCES oras ( id_oras );

ALTER TABLE bilet
    ADD CONSTRAINT bilet_clienti_fk FOREIGN KEY ( clienti_id_client )
        REFERENCES clienti ( id_client );

ALTER TABLE bilet
    ADD CONSTRAINT bilet_zbor_fk FOREIGN KEY ( zbor_id_zbor )
        REFERENCES zbor ( id_zbor );

ALTER TABLE zbor
    ADD CONSTRAINT zbor_aeroport_fk FOREIGN KEY ( aeroport_id_aeroport )
        REFERENCES aeroport ( id_aeroport );

ALTER TABLE zbor
    ADD CONSTRAINT zbor_aeroport_fkv2 FOREIGN KEY ( aeroport_id_aeroport2 )
        REFERENCES aeroport ( id_aeroport );

ALTER TABLE zbor
    ADD CONSTRAINT zbor_companie_fk FOREIGN KEY ( companie_id_companie )
        REFERENCES companie ( id_companie );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
